# Generated by Django 4.1 on 2022-09-03 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_products_options_alter_products_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='nm',
        ),
    ]
